/**
 * PH carwash / detailing bay size for the cars sold here.
 * Small · Medium · Large · Extra Large — same slugs as service_size_prices.
 *
 * Rules follow typical Hakum / PH shop charts (footprint + how the car sits in a bay),
 * not body-style marketing names. TL can still override on the ticket.
 */

export const PRICING_SIZE_SLUGS = Object.freeze(['small', 'medium', 'large', 'extra_large'])

const BIKE_MAKES = new Set(['yamaha', 'kawasaki'])

/** High-volume PH nameplates — wins over keyword fallback. */
const EXPLICIT = {
  'toyota|vios': 'small',
  'toyota|wigo': 'small',
  'toyota|raize': 'small',
  'toyota|yaris': 'small',
  'toyota|yaris cross': 'medium',
  'toyota|corolla': 'medium',
  'toyota|corolla altis': 'medium',
  'toyota|corolla cross': 'medium',
  'toyota|camry': 'medium',
  'toyota|innova': 'large',
  'toyota|fortuner': 'large',
  'toyota|rush': 'medium',
  'toyota|avanza': 'medium',
  'toyota|veloz': 'medium',
  'toyota|hilux': 'large',
  'toyota|land cruiser': 'extra_large',
  'toyota|land cruiser prado': 'large',
  'toyota|hiace': 'extra_large',
  'toyota|lite ace': 'extra_large',
  'toyota|commuter': 'extra_large',
  'toyota|grandia': 'extra_large',
  'toyota|alphard': 'extra_large',
  'toyota|granvia': 'extra_large',
  'toyota|rav4': 'large',
  'toyota|c-hr': 'small',
  'toyota|bz4x': 'medium',
  'toyota|tamaraw fx': 'extra_large',
  'toyota|revo': 'large',
  'toyota|tamaraw': 'extra_large',
  'toyota|corona': 'medium',
  'toyota|soluna': 'small',
  'toyota|echo': 'small',
  'toyota|wish': 'large',
  'toyota|previa': 'extra_large',
  'toyota|sienna': 'extra_large',
  'toyota|86': 'small',
  'toyota|gr86': 'small',
  'toyota|supra': 'large',
  'toyota|prius': 'medium',
  'toyota|crown': 'large',
  'toyota|coaster': 'extra_large',
  'mitsubishi|mirage': 'small',
  'mitsubishi|mirage g4': 'small',
  'mitsubishi|xpander': 'medium',
  'mitsubishi|xpander cross': 'medium',
  'mitsubishi|montero sport': 'large',
  'mitsubishi|pajero': 'large',
  'mitsubishi|pajero sport': 'large',
  'mitsubishi|strada': 'large',
  'mitsubishi|l300': 'extra_large',
  'mitsubishi|adventure': 'large',
  'mitsubishi|lancer': 'medium',
  'mitsubishi|lancer evolution': 'medium',
  'mitsubishi|galant': 'medium',
  'mitsubishi|space wagon': 'large',
  'mitsubishi|outlander': 'large',
  'mitsubishi|eclipse cross': 'medium',
  'mitsubishi|asx': 'medium',
  'mitsubishi|triton': 'large',
  'mitsubishi|delica': 'extra_large',
  'mitsubishi|attrage': 'small',
  'mitsubishi|fuzion': 'medium',
  'honda|brio': 'small',
  'honda|city': 'small',
  'honda|civic': 'medium',
  'honda|civic type r': 'medium',
  'honda|hr-v': 'medium',
  'honda|br-v': 'medium',
  'honda|cr-v': 'large',
  'honda|wr-v': 'small',
  'honda|accord': 'medium',
  'honda|mobilio': 'medium',
  'honda|jazz': 'small',
  'honda|fit': 'small',
  'honda|pilot': 'large',
  'honda|odyssey': 'extra_large',
  'honda|pilot hybrid': 'large',
  'honda|city hatchback': 'small',
  'honda|cr-z': 'small',
  'honda|insight': 'small',
  'nissan|almera': 'small',
  'nissan|kicks': 'medium',
  'nissan|terra': 'large',
  'nissan|navara': 'large',
  'nissan|patrol': 'extra_large',
  'nissan|urvan': 'extra_large',
  'nissan|livina': 'medium',
  'nissan|juke': 'small',
  'nissan|x-trail': 'large',
  'nissan|sentra': 'small',
  'nissan|cefiro': 'medium',
  'nissan|primera': 'medium',
  'nissan|sunny': 'small',
  'nissan|frontier': 'large',
  'nissan|patrol royale': 'extra_large',
  'nissan|gt-r': 'large',
  'nissan|leaf': 'medium',
  'nissan|sylphy': 'medium',
  'hyundai|accent': 'small',
  'hyundai|reina': 'small',
  'hyundai|i10': 'small',
  'hyundai|i20': 'small',
  'hyundai|getz': 'small',
  'hyundai|eon': 'small',
  'hyundai|venue': 'small',
  'hyundai|creta': 'medium',
  'hyundai|tucson': 'medium',
  'hyundai|santa fe': 'large',
  'hyundai|stargazer': 'medium',
  'hyundai|stargazer x': 'medium',
  'hyundai|staria': 'extra_large',
  'hyundai|palisade': 'extra_large',
  'hyundai|kona': 'medium',
  'hyundai|elantra': 'medium',
  'hyundai|sonata': 'medium',
  'hyundai|ioniq 5': 'medium',
  'hyundai|ioniq 6': 'medium',
  'hyundai|h100': 'extra_large',
  'hyundai|h-1': 'extra_large',
  'hyundai|grand starex': 'extra_large',
  'hyundai|porter': 'extra_large',
  'ford|ranger': 'large',
  'ford|everest': 'large',
  'ford|territory': 'medium',
  'ford|explorer': 'large',
  'ford|mustang': 'large',
  'ford|transit': 'extra_large',
  'ford|bronco': 'large',
  'ford|ecosport': 'medium',
  'ford|escape': 'medium',
  'ford|focus': 'small',
  'ford|fiesta': 'small',
  'ford|laser': 'small',
  'ford|lynx': 'small',
  'ford|ranger raptor': 'large',
  'ford|expedition': 'extra_large',
  'ford|f-150': 'extra_large',
  'suzuki|swift': 'small',
  'suzuki|dzire': 'small',
  'suzuki|ertiga': 'medium',
  'suzuki|xl7': 'medium',
  'suzuki|jimny': 'small',
  'suzuki|s-presso': 'small',
  'suzuki|celerio': 'small',
  'suzuki|vitara': 'medium',
  'suzuki|grand vitara': 'medium',
  'suzuki|carry': 'medium',
  'suzuki|apv': 'large',
  'suzuki|alto': 'small',
  'suzuki|wagon r': 'small',
  'suzuki|kizashi': 'medium',
  'suzuki|sx4': 'small',
  'suzuki|baleno': 'small',
  'suzuki|ignis': 'small',
  'suzuki|s-cross': 'medium',
  'kia|soluto': 'small',
  'kia|rio': 'small',
  'kia|seltos': 'medium',
  'kia|sportage': 'medium',
  'kia|sorento': 'large',
  'kia|carnival': 'extra_large',
  'kia|picanto': 'small',
  'kia|stonic': 'small',
  'kia|pride': 'small',
  'kia|spectra': 'medium',
  'kia|carens': 'medium',
  'kia|soul': 'small',
  'kia|forte': 'medium',
  'kia|k5': 'medium',
  'kia|ev6': 'medium',
  'kia|ev9': 'large',
  'kia|besta': 'extra_large',
  'kia|pregio': 'extra_large',
  'mazda|mazda2': 'small',
  'mazda|mazda3': 'medium',
  'mazda|cx-3': 'small',
  'mazda|cx-30': 'medium',
  'mazda|cx-5': 'large',
  'mazda|cx-60': 'large',
  'mazda|cx-8': 'large',
  'mazda|cx-9': 'large',
  'mazda|bt-50': 'large',
  'mazda|mx-5': 'small',
  'mazda|mazda6': 'medium',
  'mazda|familia': 'small',
  'mazda|323': 'small',
  'mazda|626': 'medium',
  'mazda|premacy': 'medium',
  'mazda|mpv': 'large',
  'mazda|cx-7': 'large',
  'mazda|rx-8': 'medium',
  'isuzu|d-max': 'large',
  'isuzu|mu-x': 'large',
  'isuzu|traviz': 'medium',
  'isuzu|crosswind': 'large',
  'isuzu|hi-lander': 'large',
  'isuzu|trooper': 'large',
  'isuzu|panther': 'large',
  'isuzu|n-series': 'extra_large',
  'isuzu|f-series': 'extra_large',
  'isuzu|elf': 'extra_large',
  'isuzu|npr': 'extra_large',
  'chevrolet|spark': 'small',
  'chevrolet|sail': 'small',
  'chevrolet|trailblazer': 'large',
  'chevrolet|colorado': 'large',
  'chevrolet|suburban': 'extra_large',
  'chevrolet|tahoe': 'extra_large',
  'chevrolet|captiva': 'large',
  'chevrolet|aveo': 'small',
  'chevrolet|optra': 'medium',
  'chevrolet|cruze': 'medium',
  'chevrolet|orlando': 'large',
  'chevrolet|spin': 'medium',
  'chevrolet|tavera': 'large',
  'chevrolet|blazer': 'large',
  'mg|mg5': 'medium',
  'mg|zs': 'medium',
  'mg|hs': 'medium',
  'mg|rx5': 'medium',
  'mg|gt': 'medium',
  'mg|one': 'medium',
  'mg|cyberster': 'small',
  'mg|g50': 'extra_large',
  'mg|v80': 'extra_large',
  'mg|3': 'small',
  'mg|6': 'medium',
  'mg|rx8': 'medium',
  'geely|coolray': 'medium',
  'geely|okavango': 'large',
  'geely|emgrand': 'medium',
  'geely|gx3 pro': 'small',
  'geely|azkarra': 'medium',
  'geely|geometry c': 'medium',
  'geely|preface': 'medium',
  'geely|monjaro': 'large',
  'byd|atto 3': 'medium',
  'byd|seal': 'medium',
  'byd|sealion 6': 'large',
  'byd|sealion 7': 'large',
  'byd|dolphin': 'small',
  'byd|tang': 'large',
  'byd|han': 'large',
  'byd|shark': 'large',
  'byd|m6': 'extra_large',
  'byd|emax 7': 'extra_large',
  'byd|seal u': 'medium',
  'chery|tiggo 2 pro': 'medium',
  'chery|tiggo 4 pro': 'medium',
  'chery|tiggo 5x': 'medium',
  'chery|tiggo 7 pro': 'large',
  'chery|tiggo 8 pro': 'large',
  'chery|arrizo 5': 'medium',
  'chery|omoda 5': 'medium',
  'chery|omoda e5': 'medium',
  'chery|jaecoo j7': 'large',
  'chery|qq': 'small',
  'subaru|impreza': 'medium',
  'subaru|legacy': 'medium',
  'subaru|outback': 'large',
  'subaru|forester': 'large',
  'subaru|xv': 'medium',
  'subaru|crosstrek': 'medium',
  'subaru|wrx': 'medium',
  'subaru|brz': 'small',
  'subaru|ascent': 'large',
  'subaru|levorg': 'medium',
  'volkswagen|polo': 'small',
  'volkswagen|golf': 'medium',
  'volkswagen|jetta': 'medium',
  'volkswagen|tiguan': 'large',
  'volkswagen|teramont': 'extra_large',
  'volkswagen|t-cross': 'medium',
  'volkswagen|passat': 'medium',
  'volkswagen|touareg': 'extra_large',
  'volkswagen|multivan': 'extra_large',
  'bmw|1 series': 'small',
  'bmw|2 series': 'medium',
  'bmw|3 series': 'medium',
  'bmw|5 series': 'large',
  'bmw|7 series': 'large',
  'bmw|x1': 'medium',
  'bmw|x3': 'large',
  'bmw|x5': 'large',
  'bmw|x6': 'large',
  'bmw|x7': 'extra_large',
  'bmw|ix': 'large',
  'bmw|i4': 'medium',
  'bmw|ix3': 'large',
  'mercedes-benz|a-class': 'small',
  'mercedes-benz|c-class': 'medium',
  'mercedes-benz|e-class': 'large',
  'mercedes-benz|s-class': 'large',
  'mercedes-benz|gla': 'medium',
  'mercedes-benz|glb': 'medium',
  'mercedes-benz|glc': 'large',
  'mercedes-benz|gle': 'large',
  'mercedes-benz|gls': 'extra_large',
  'mercedes-benz|v-class': 'extra_large',
  'mercedes-benz|g-class': 'extra_large',
  'mercedes-benz|cla': 'medium',
  'audi|a3': 'small',
  'audi|a4': 'medium',
  'audi|a6': 'large',
  'audi|q2': 'small',
  'audi|q3': 'medium',
  'audi|q5': 'large',
  'audi|q7': 'extra_large',
  'audi|q8': 'extra_large',
  'audi|e-tron': 'large',
  'audi|a5': 'medium',
  'audi|tt': 'small',
  'lexus|is': 'medium',
  'lexus|es': 'medium',
  'lexus|ls': 'large',
  'lexus|nx': 'medium',
  'lexus|rx': 'large',
  'lexus|ux': 'small',
  'lexus|lx': 'extra_large',
  'lexus|lm': 'extra_large',
  'lexus|gx': 'large',
  'lexus|rc': 'medium',
  'peugeot|2008': 'medium',
  'peugeot|3008': 'medium',
  'peugeot|5008': 'large',
  'peugeot|landtrek': 'large',
  'peugeot|expert': 'extra_large',
  'peugeot|traveller': 'extra_large',
  'peugeot|208': 'small',
  'peugeot|308': 'medium',
  'foton|toplander': 'large',
  'foton|thunder': 'large',
  'foton|view': 'extra_large',
  'foton|transvan': 'extra_large',
  'foton|gratour': 'extra_large',
  'foton|tornado': 'large',
  'foton|sauvana': 'large',
  'hino|300 series': 'extra_large',
  'hino|500 series': 'extra_large',
  'hino|dutro': 'extra_large',
  'hino|ranger': 'extra_large',
  'gac|gs3': 'medium',
  'gac|gs4': 'large',
  'gac|emzoom': 'medium',
  'gac|emkoo': 'large',
  'gac|m8': 'extra_large',
  'gac|gn8': 'extra_large',
  'gac|aion y': 'medium',
  'gac|aion v': 'medium',
  'jetour|dashing': 'medium',
  'jetour|x70': 'large',
  'jetour|x70 plus': 'large',
  'jetour|x90 plus': 'large',
  'jetour|t2': 'large',
  'jetour|dashing i-dm': 'medium',
  'gwm|cannon': 'large',
  'gwm|haval h6': 'large',
  'gwm|haval jolion': 'medium',
  'gwm|tank 300': 'large',
  'gwm|ora good cat': 'small',
  'gwm|poer': 'large',
  'gwm|wey': 'large',
  'great wall|cannon': 'large',
  'great wall|poer': 'large',
  'great wall|wingle': 'large',
  'great wall|steed': 'large',
  'changan|alsvin': 'small',
  'changan|cs15': 'small',
  'changan|cs35 plus': 'medium',
  'changan|cs55 plus': 'medium',
  'changan|uni-t': 'medium',
  'changan|uni-v': 'medium',
  'changan|hunter': 'large',
  'changan|nevo a05': 'medium',
  'dongfeng|rich': 'large',
  'dongfeng|ax7': 'large',
  'dongfeng|glory': 'medium',
  'dongfeng|captain': 'large',
  'dongfeng|mango': 'small',
  'dongfeng|nammi 01': 'small',
  'tesla|model 3': 'medium',
  'tesla|model y': 'medium',
  'tesla|model s': 'large',
  'tesla|model x': 'extra_large',
  'volvo|xc40': 'medium',
  'volvo|xc60': 'large',
  'volvo|xc90': 'large',
  'volvo|s60': 'medium',
  'volvo|s90': 'large',
  'volvo|c40': 'medium',
  'volvo|ex30': 'small',
  'volvo|ex90': 'large',
  'jeep|wrangler': 'large',
  'jeep|gladiator': 'large',
  'jeep|cherokee': 'large',
  'jeep|grand cherokee': 'large',
  'jeep|compass': 'medium',
  'jeep|renegade': 'medium',
  'porsche|911': 'small',
  'porsche|cayenne': 'large',
  'porsche|macan': 'large',
  'porsche|panamera': 'large',
  'porsche|taycan': 'medium',
  'porsche|718': 'small',
  'ssangyong|musso': 'large',
  'ssangyong|rexton': 'large',
  'ssangyong|tivoli': 'medium',
  'ssangyong|korando': 'medium',
  'ssangyong|actyon': 'large',
  'ssangyong|musso grand': 'large',
  'ssangyong|rexton sports': 'large',
  'daihatsu|terios': 'medium',
  'daihatsu|xenia': 'medium',
  'daihatsu|gran max': 'extra_large',
  'daihatsu|hijet': 'medium',
  'daihatsu|rocky': 'small',
  'proton|saga': 'small',
  'proton|persona': 'small',
  'proton|x50': 'medium',
  'proton|x70': 'large',
  'proton|exora': 'medium',
  'proton|waja': 'medium',
  'fuso|canter': 'extra_large',
  'fuso|fighter': 'extra_large',
  'fuso|rosa': 'extra_large',
  'maxus|g10': 'extra_large',
  'maxus|g50': 'extra_large',
  'maxus|d60': 'medium',
  'maxus|t60': 'large',
  'maxus|deliver 9': 'extra_large',
  'maxus|mifa 9': 'extra_large',
  'baic|x55': 'medium',
  'baic|bj40': 'large',
  'baic|eu5': 'medium',
  'baic|beijing x7': 'medium',
  'wuling|almaz': 'large',
  'wuling|cortez': 'extra_large',
  'wuling|confero': 'extra_large',
  'wuling|air ev': 'small',
  'wuling|binguo ev': 'small',
  'wuling|mini ev': 'small',
  'vinfast|vf 5': 'small',
  'vinfast|vf 6': 'medium',
  'vinfast|vf 7': 'medium',
  'vinfast|vf 8': 'large',
  'vinfast|vf 9': 'large',
  'vinfast|vf e34': 'medium',
  'dfsk|glory 580': 'large',
  'dfsk|glory i-auto': 'medium',
  'dfsk|gelora': 'extra_large',
  'dfsk|c37': 'extra_large',
  'dfsk|super cab': 'large',
  'jac|t8': 'large',
  'jac|js4': 'medium',
  'jac|x200': 'extra_large',
  'jac|sunray': 'extra_large',
  'mahindra|xuv300': 'medium',
  'mahindra|xuv500': 'large',
  'mahindra|scorpio': 'large',
  'mahindra|bolero': 'large',
  'mahindra|thar': 'large',
  'mahindra|kuv100': 'small',
  'haima|m3': 'medium',
  'haima|s5': 'medium',
  'haima|7x': 'large',
  'haima|8s': 'medium',
  'opel|astra': 'small',
  'opel|corsa': 'small',
  'opel|zafira': 'medium',
  'opel|vectra': 'medium',
  'chrysler|300c': 'large',
  'chrysler|pt cruiser': 'small',
  'chrysler|voyager': 'extra_large',
  'chrysler|grand voyager': 'extra_large',
  'dodge|journey': 'large',
  'dodge|durango': 'large',
  'dodge|challenger': 'large',
  'dodge|ram': 'extra_large',
}

const XL_TOKENS = [
  'alphard', 'grandia', 'hiace', 'commuter', 'granvia', 'coaster', 'lite ace', 'tamaraw',
  'previa', 'sienna', 'odyssey', 'carnival', 'staria', 'urvan', 'l300', 'delica', 'starex',
  'h100', 'h-1', 'porter', 'transit', 'expedition', 'f-150', 'suburban', 'tahoe', 'palisade',
  'v-class', 'g-class', 'multivan', 'teramont', 'touareg', 'model x', 'sunray', 'gelora',
  'cortez', 'confero', 'transvan', 'gratour', 'canter', 'dutro', 'n-series', 'f-series',
  'fighter', 'rosa', 'mifa', 'deliver 9', 'emax 7',
]

const LARGE_TOKENS = [
  'fortuner', 'montero', 'pajero', 'everest', 'terra', 'cr-v', 'rav4', 'cx-5', 'cx-8', 'cx-9',
  'cx-60', 'santa fe', 'mu-x', 'innova', 'hilux', 'ranger', 'navara', 'strada', 'd-max',
  'triton', 'colorado', 'bt-50', 'landtrek', 'cannon', 'poer', 'wingle', 'trailblazer',
  'explorer', 'bronco', 'outlander', 'sorento', 'forester', 'outback', 'tiguan', 'wrangler',
  'gladiator', 'cayenne', 'macan', 'okavango', 'tiggo 7', 'tiggo 8', 'sealion 7', 'prado',
  'land cruiser', 'xc90', 'xc60', 'mustang', 'supra', 'rexton', 'musso', 'tank 300',
  'haval h6', 'x70', 'x90', 'glory 580', 'almaz', 'vf 8', 'vf 9', 'thar', 'scorpio',
]

const SMALL_TOKENS = [
  'wigo', 'mirage', 'brio', 'swift', 'celerio', 'picanto', 'i10', 'i20', 'getz', 'eon',
  'spark', 'almera', 'vios', 'accent', 'reina', 'soluto', 'dzire', 'jazz', 'fit', 'mazda2',
  'polo', 'yaris', 'echo', 'soluna', 'sail', 'aveo', 'picanto', 's-presso', 'alto',
  'wagon r', 'ignis', 'baleno', 'corsa', 'saga', 'persona', 'air ev', 'mini ev', 'binguo',
  'vf 5', 'alsvin', 'cs15', 'good cat', 'raize', 'wr-v', 'venue', 'stonic', 'jimny',
  'fiesta', 'sunny', 'sentra', 'cr-z', 'insight', 'dolphin', 'juke', 'cx-3', 'a3', 'q2',
]

function tokenHit(model, tokens) {
  const n = String(model || '').trim().toLowerCase()
  if (!n) return false
  return tokens.some((t) => n === t || (t.length >= 4 && n.includes(t)))
}

export function inferPhPricingSize(make, model) {
  const mk = String(make || '').trim().toLowerCase()
  const md = String(model || '').trim().toLowerCase()
  if (EXPLICIT[`${mk}|${md}`]) return EXPLICIT[`${mk}|${md}`]
  if (BIKE_MAKES.has(mk)) return 'small'
  if (tokenHit(md, XL_TOKENS) || tokenHit(`${mk} ${md}`, XL_TOKENS)) return 'extra_large'
  if (tokenHit(md, LARGE_TOKENS)) return 'large'
  if (tokenHit(md, SMALL_TOKENS) || md === 'city' || md === 'rio' || md === '3') return 'small'
  return 'medium'
}

export function catalogSizeKey(make, model) {
  return `${String(make || '').trim().toLowerCase()}|${String(model || '').trim().toLowerCase()}`
}
