import {TINT_QUESTIONS,TINT_DISCLAIMERS,TINT_VEHICLES,tintPeso,recommendTint,orderedBenefits,buildTintLead} from './finder-engine.js';
const config=await fetch('catalog.json').then(r=>{if(!r.ok)throw Error('Catalog unavailable');return r.json()});
const quiz=document.querySelector('.quiz'),results=document.querySelector('#results'),dialog=document.querySelector('#booking');
let step=0,answers={},selected;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function benefits(){document.querySelector('.benefits').innerHTML=orderedBenefits(config,answers).map(b=>`<article><img src="assets/icon-${b.id}.png" alt="" loading="lazy"><div>${b.personalized?'<span class="personal">FOR YOUR PRIORITIES</span>':''}<h3>${esc(b.title)}</h3><p>${esc(b.description)}</p></div></article>`).join('')}
function render(){const q=TINT_QUESTIONS[step];document.querySelectorAll('.steps li').forEach((li,i)=>{li.classList.toggle('active',i===step);li.classList.toggle('done',!!answers[TINT_QUESTIONS[i].key])});quiz.innerHTML=`<div class="quiz-meta"><span>STEP 0${step+1} / 04</span><span>YOUR DRIVE, YOUR CHOICE</span></div><progress value="${step+1}" max="4" aria-label="Question progress"></progress><h3>${esc(q.title)}</h3><p>${esc(q.hint)}</p><fieldset><legend class="sr-only">${esc(q.title)}</legend>${q.choices.map(c=>`<label class="choice"><input type="radio" name="${q.key}" value="${c.id}" ${answers[q.key]===c.id?'checked':''}><span><strong>${esc(c.label)}</strong>${c.description?`<small>${esc(c.description)}</small>`:''}</span><i aria-hidden="true">↗</i></label>`).join('')}</fieldset><div class="quiz-controls"><button class="text-button" id="back" ${step===0?'disabled':''}>← Back</button><button class="button" id="next" ${!answers[q.key]?'disabled':''}>${step===3?'Show my options':'Continue'} ↗</button></div>`;quiz.querySelectorAll('input').forEach(r=>r.onchange=()=>{answers[q.key]=r.value;quiz.querySelector('#next').disabled=false});quiz.querySelector('#back').onclick=()=>{step--;render()};quiz.querySelector('#next').onclick=()=>{if(!answers[q.key])return;if(step<3){step++;render()}else showResults()}}
function specs(f){return `<div class="film-specs">${[['VLT',f.vlt],['TSER',f.tser],['IRR',f.irr],['UVR',f.uvr]].map(([k,v])=>`<div><strong>${esc(v)}%</strong><small>${k}</small></div>`).join('')}</div>`}
function showResults(){const opts=recommendTint(config,answers);results.hidden=false;document.querySelector('.answer-summary').textContent=TINT_QUESTIONS.map(q=>q.choices.find(c=>c.id===answers[q.key]).label).join(' · ');document.querySelector('.result-grid').innerHTML=opts.map((o,i)=>{const p=config.packages[o.package];return `<article class="result-card"><div class="result-title"><span class="eyebrow">OPTION 0${i+1} / ${o.id}</span><h3>${esc(p.name)}</h3><p>${esc(p.warranty)} warranty</p></div><div class="film-pair"><div><span class="zone">FRONT WINDSHIELD + FRONT DOORS</span><h4>${esc(config.films[o.front].name)}</h4>${specs(config.films[o.front])}</div><div><span class="zone">REAR DOORS + REAR WINDSHIELD</span><h4>${esc(config.films[o.rear].name)}</h4>${specs(config.films[o.rear])}</div></div><div class="price"><span>Full-window package / ${esc(TINT_VEHICLES.find(v=>v.id===answers.vehicle).label)}</span><strong>${tintPeso(o.price)}</strong></div><details class="price-list"><summary>Compare all vehicle prices</summary><table><caption>${esc(p.name)} package reference prices</caption><tbody>${TINT_VEHICLES.map(v=>`<tr class="${v.id===answers.vehicle?'selected':''}"><th scope="row">${esc(v.label)}</th><td>${tintPeso(p.prices[v.id])}</td></tr>`).join('')}</tbody></table></details><div class="result-actions"><button class="button book" data-option="${o.id}">Choose this tint ↗</button><button class="text-button message" data-option="${o.id}">Preview sales enquiry</button></div></article>`}).join('');document.querySelector('.terms ul').innerHTML=TINT_DISCLAIMERS.map(d=>`<li>${esc(d)}</li>`).join('');benefits();document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>openBooking(opts.find(o=>o.id===b.dataset.option)));results.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'})}
function openBooking(o){selected=o;dialog.querySelector('form').hidden=false;dialog.querySelector('.success').hidden=true;dialog.querySelector('.form-error').textContent='';dialog.querySelector('.booking-choice').textContent=`${config.packages[o.package].name} · ${o.front} / ${o.rear} · ${tintPeso(o.price)}`;dialog.showModal()}
document.querySelector('#restart').onclick=()=>{step=0;render();document.querySelector('#finder').scrollIntoView({behavior:'smooth'})};dialog.querySelector('.close').onclick=()=>dialog.close();dialog.querySelector('.close-success').onclick=()=>dialog.close();dialog.querySelector('[name=preferredDate]').min=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'});dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.acknowledged=e.target.acknowledged.checked;body.answers=answers;body.optionId=selected.id;const result=buildTintLead(body,config);if(result.error){dialog.querySelector('.form-error').textContent=result.error;return}e.target.hidden=true;dialog.querySelector('.success').hidden=false;dialog.querySelector('.success').focus()};render();benefits();
