-- Resync vehicle_catalog sizes to body-style bay chart + seed S/M/L/XL on bay SKUs.
-- Small=sedan/hatch · Medium=crossover · Large=SUV/pickup/MPV · XL=full-size van/people mover.
-- Bay price ratios match detailing: 0.85 / 1 / 1.2 / 1.4 of Medium (services.price_minor).

update public.vehicle_catalog vc
set size_slug = v.size_slug,
    updated_at = now()
from (values
  ('Audi', 'A3', 'small'),
  ('Audi', 'A4', 'medium'),
  ('Audi', 'A6', 'large'),
  ('Audi', 'Q2', 'medium'),
  ('Audi', 'Q3', 'medium'),
  ('Audi', 'Q5', 'large'),
  ('Audi', 'Q7', 'extra_large'),
  ('Audi', 'Q8', 'extra_large'),
  ('Audi', 'e-tron', 'large'),
  ('Audi', 'A5', 'medium'),
  ('Audi', 'TT', 'small'),
  ('BAIC', 'X55', 'medium'),
  ('BAIC', 'BJ40', 'large'),
  ('BAIC', 'EU5', 'small'),
  ('BAIC', 'Beijing X7', 'medium'),
  ('BMW', '1 Series', 'small'),
  ('BMW', '2 Series', 'small'),
  ('BMW', '3 Series', 'medium'),
  ('BMW', '5 Series', 'large'),
  ('BMW', '7 Series', 'large'),
  ('BMW', 'X1', 'medium'),
  ('BMW', 'X3', 'large'),
  ('BMW', 'X5', 'large'),
  ('BMW', 'X6', 'large'),
  ('BMW', 'X7', 'extra_large'),
  ('BMW', 'iX', 'large'),
  ('BMW', 'i4', 'small'),
  ('BMW', 'iX3', 'large'),
  ('BYD', 'Atto 3', 'medium'),
  ('BYD', 'Seal', 'small'),
  ('BYD', 'Sealion 6', 'large'),
  ('BYD', 'Sealion 7', 'large'),
  ('BYD', 'Dolphin', 'small'),
  ('BYD', 'Tang', 'large'),
  ('BYD', 'Han', 'large'),
  ('BYD', 'Shark', 'large'),
  ('BYD', 'M6', 'extra_large'),
  ('BYD', 'eMAX 7', 'extra_large'),
  ('BYD', 'Seal U', 'medium'),
  ('Changan', 'Alsvin', 'small'),
  ('Changan', 'CS15', 'medium'),
  ('Changan', 'CS35 Plus', 'medium'),
  ('Changan', 'CS55 Plus', 'medium'),
  ('Changan', 'UNI-T', 'medium'),
  ('Changan', 'UNI-V', 'small'),
  ('Changan', 'Hunter', 'large'),
  ('Changan', 'Nevo A05', 'small'),
  ('Chery', 'Tiggo 2 Pro', 'medium'),
  ('Chery', 'Tiggo 4 Pro', 'medium'),
  ('Chery', 'Tiggo 5x', 'medium'),
  ('Chery', 'Tiggo 7 Pro', 'large'),
  ('Chery', 'Tiggo 8 Pro', 'large'),
  ('Chery', 'Arrizo 5', 'small'),
  ('Chery', 'Omoda 5', 'medium'),
  ('Chery', 'Omoda E5', 'medium'),
  ('Chery', 'Jaecoo J7', 'large'),
  ('Chery', 'QQ', 'small'),
  ('Chevrolet', 'Spark', 'small'),
  ('Chevrolet', 'Sail', 'small'),
  ('Chevrolet', 'Trailblazer', 'large'),
  ('Chevrolet', 'Colorado', 'large'),
  ('Chevrolet', 'Suburban', 'extra_large'),
  ('Chevrolet', 'Tahoe', 'extra_large'),
  ('Chevrolet', 'Captiva', 'large'),
  ('Chevrolet', 'Aveo', 'small'),
  ('Chevrolet', 'Optra', 'small'),
  ('Chevrolet', 'Cruze', 'small'),
  ('Chevrolet', 'Orlando', 'large'),
  ('Chevrolet', 'Spin', 'medium'),
  ('Chevrolet', 'Tavera', 'large'),
  ('Chevrolet', 'Blazer', 'large'),
  ('Chrysler', '300C', 'large'),
  ('Chrysler', 'PT Cruiser', 'small'),
  ('Chrysler', 'Voyager', 'extra_large'),
  ('Chrysler', 'Grand Voyager', 'extra_large'),
  ('Daihatsu', 'Terios', 'medium'),
  ('Daihatsu', 'Xenia', 'medium'),
  ('Daihatsu', 'Gran Max', 'extra_large'),
  ('Daihatsu', 'Hijet', 'medium'),
  ('Daihatsu', 'Rocky', 'medium'),
  ('DFSK', 'Glory 580', 'large'),
  ('DFSK', 'Glory i-Auto', 'medium'),
  ('DFSK', 'Gelora', 'extra_large'),
  ('DFSK', 'C37', 'extra_large'),
  ('DFSK', 'Super Cab', 'large'),
  ('Dodge', 'Journey', 'large'),
  ('Dodge', 'Durango', 'large'),
  ('Dodge', 'Challenger', 'large'),
  ('Dodge', 'Ram', 'extra_large'),
  ('Dongfeng', 'Rich', 'large'),
  ('Dongfeng', 'AX7', 'large'),
  ('Dongfeng', 'Glory', 'medium'),
  ('Dongfeng', 'Captain', 'large'),
  ('Dongfeng', 'Mango', 'small'),
  ('Dongfeng', 'Nammi 01', 'small'),
  ('Ford', 'Ranger', 'large'),
  ('Ford', 'Everest', 'large'),
  ('Ford', 'Territory', 'medium'),
  ('Ford', 'Explorer', 'large'),
  ('Ford', 'Mustang', 'large'),
  ('Ford', 'Transit', 'extra_large'),
  ('Ford', 'Bronco', 'large'),
  ('Ford', 'EcoSport', 'medium'),
  ('Ford', 'Escape', 'medium'),
  ('Ford', 'Focus', 'small'),
  ('Ford', 'Fiesta', 'small'),
  ('Ford', 'Laser', 'small'),
  ('Ford', 'Lynx', 'small'),
  ('Ford', 'Ranger Raptor', 'large'),
  ('Ford', 'Expedition', 'extra_large'),
  ('Ford', 'F-150', 'extra_large'),
  ('Foton', 'Toplander', 'large'),
  ('Foton', 'Thunder', 'large'),
  ('Foton', 'View', 'extra_large'),
  ('Foton', 'Transvan', 'extra_large'),
  ('Foton', 'Gratour', 'extra_large'),
  ('Foton', 'Tornado', 'large'),
  ('Foton', 'Sauvana', 'large'),
  ('Fuso', 'Canter', 'extra_large'),
  ('Fuso', 'Fighter', 'extra_large'),
  ('Fuso', 'Rosa', 'extra_large'),
  ('GAC', 'GS3', 'medium'),
  ('GAC', 'GS4', 'large'),
  ('GAC', 'Emzoom', 'medium'),
  ('GAC', 'Emkoo', 'large'),
  ('GAC', 'M8', 'extra_large'),
  ('GAC', 'GN8', 'extra_large'),
  ('GAC', 'Aion Y', 'medium'),
  ('GAC', 'Aion V', 'medium'),
  ('Geely', 'Coolray', 'medium'),
  ('Geely', 'Okavango', 'large'),
  ('Geely', 'Emgrand', 'small'),
  ('Geely', 'GX3 Pro', 'medium'),
  ('Geely', 'Azkarra', 'medium'),
  ('Geely', 'Geometry C', 'medium'),
  ('Geely', 'Preface', 'medium'),
  ('Geely', 'Monjaro', 'large'),
  ('Great Wall', 'Cannon', 'large'),
  ('Great Wall', 'Poer', 'large'),
  ('Great Wall', 'Wingle', 'large'),
  ('Great Wall', 'Steed', 'large'),
  ('GWM', 'Cannon', 'large'),
  ('GWM', 'Haval H6', 'large'),
  ('GWM', 'Haval Jolion', 'medium'),
  ('GWM', 'Tank 300', 'large'),
  ('GWM', 'Ora Good Cat', 'small'),
  ('GWM', 'Poer', 'large'),
  ('GWM', 'Wey', 'large'),
  ('Haima', 'M3', 'small'),
  ('Haima', 'S5', 'medium'),
  ('Haima', '7X', 'large'),
  ('Haima', '8S', 'medium'),
  ('Hino', '300 Series', 'extra_large'),
  ('Hino', '500 Series', 'extra_large'),
  ('Hino', 'Dutro', 'extra_large'),
  ('Hino', 'Ranger', 'extra_large'),
  ('Honda', 'Brio', 'small'),
  ('Honda', 'City', 'small'),
  ('Honda', 'Civic', 'small'),
  ('Honda', 'Civic Type R', 'small'),
  ('Honda', 'HR-V', 'medium'),
  ('Honda', 'BR-V', 'medium'),
  ('Honda', 'CR-V', 'large'),
  ('Honda', 'WR-V', 'medium'),
  ('Honda', 'Accord', 'medium'),
  ('Honda', 'Mobilio', 'medium'),
  ('Honda', 'Jazz', 'small'),
  ('Honda', 'Fit', 'small'),
  ('Honda', 'Pilot', 'large'),
  ('Honda', 'Odyssey', 'extra_large'),
  ('Honda', 'Pilot Hybrid', 'large'),
  ('Honda', 'City Hatchback', 'small'),
  ('Honda', 'CR-Z', 'small'),
  ('Honda', 'Insight', 'small'),
  ('Hyundai', 'Accent', 'small'),
  ('Hyundai', 'Reina', 'small'),
  ('Hyundai', 'i10', 'small'),
  ('Hyundai', 'i20', 'small'),
  ('Hyundai', 'Getz', 'small'),
  ('Hyundai', 'Eon', 'small'),
  ('Hyundai', 'Venue', 'medium'),
  ('Hyundai', 'Creta', 'medium'),
  ('Hyundai', 'Tucson', 'large'),
  ('Hyundai', 'Santa Fe', 'large'),
  ('Hyundai', 'Stargazer', 'medium'),
  ('Hyundai', 'Stargazer X', 'medium'),
  ('Hyundai', 'Staria', 'extra_large'),
  ('Hyundai', 'Palisade', 'extra_large'),
  ('Hyundai', 'Kona', 'medium'),
  ('Hyundai', 'Elantra', 'small'),
  ('Hyundai', 'Sonata', 'medium'),
  ('Hyundai', 'Ioniq 5', 'medium'),
  ('Hyundai', 'Ioniq 6', 'small'),
  ('Hyundai', 'H100', 'extra_large'),
  ('Hyundai', 'H-1', 'extra_large'),
  ('Hyundai', 'Grand Starex', 'extra_large'),
  ('Hyundai', 'Porter', 'extra_large'),
  ('Isuzu', 'D-Max', 'large'),
  ('Isuzu', 'mu-X', 'large'),
  ('Isuzu', 'Traviz', 'medium'),
  ('Isuzu', 'Crosswind', 'large'),
  ('Isuzu', 'Hi-Lander', 'large'),
  ('Isuzu', 'Trooper', 'large'),
  ('Isuzu', 'Panther', 'large'),
  ('Isuzu', 'N-Series', 'extra_large'),
  ('Isuzu', 'F-Series', 'extra_large'),
  ('Isuzu', 'Elf', 'extra_large'),
  ('Isuzu', 'NPR', 'extra_large'),
  ('JAC', 'T8', 'large'),
  ('JAC', 'JS4', 'medium'),
  ('JAC', 'X200', 'extra_large'),
  ('JAC', 'Sunray', 'extra_large'),
  ('Jeep', 'Wrangler', 'large'),
  ('Jeep', 'Gladiator', 'large'),
  ('Jeep', 'Cherokee', 'large'),
  ('Jeep', 'Grand Cherokee', 'large'),
  ('Jeep', 'Compass', 'medium'),
  ('Jeep', 'Renegade', 'medium'),
  ('Jetour', 'Dashing', 'medium'),
  ('Jetour', 'X70', 'large'),
  ('Jetour', 'X70 Plus', 'large'),
  ('Jetour', 'X90 Plus', 'large'),
  ('Jetour', 'T2', 'large'),
  ('Jetour', 'Dashing i-DM', 'medium'),
  ('Kawasaki', 'Barako', 'small'),
  ('Kawasaki', 'Rouser', 'small'),
  ('Kawasaki', 'Ninja 400', 'small'),
  ('Kawasaki', 'Z400', 'small'),
  ('Kawasaki', 'KLX', 'small'),
  ('Kawasaki', 'CT100', 'small'),
  ('Kia', 'Soluto', 'small'),
  ('Kia', 'Rio', 'small'),
  ('Kia', 'Seltos', 'medium'),
  ('Kia', 'Sportage', 'large'),
  ('Kia', 'Sorento', 'large'),
  ('Kia', 'Carnival', 'extra_large'),
  ('Kia', 'Picanto', 'small'),
  ('Kia', 'Stonic', 'medium'),
  ('Kia', 'Pride', 'small'),
  ('Kia', 'Spectra', 'small'),
  ('Kia', 'Carens', 'medium'),
  ('Kia', 'Soul', 'medium'),
  ('Kia', 'Forte', 'small'),
  ('Kia', 'K5', 'medium'),
  ('Kia', 'EV6', 'medium'),
  ('Kia', 'EV9', 'large'),
  ('Kia', 'Besta', 'extra_large'),
  ('Kia', 'Pregio', 'extra_large'),
  ('Lexus', 'IS', 'small'),
  ('Lexus', 'ES', 'medium'),
  ('Lexus', 'LS', 'large'),
  ('Lexus', 'NX', 'medium'),
  ('Lexus', 'RX', 'large'),
  ('Lexus', 'UX', 'medium'),
  ('Lexus', 'LX', 'extra_large'),
  ('Lexus', 'LM', 'extra_large'),
  ('Lexus', 'GX', 'large'),
  ('Lexus', 'RC', 'small'),
  ('Mahindra', 'XUV300', 'medium'),
  ('Mahindra', 'XUV500', 'large'),
  ('Mahindra', 'Scorpio', 'large'),
  ('Mahindra', 'Bolero', 'large'),
  ('Mahindra', 'Thar', 'large'),
  ('Mahindra', 'KUV100', 'small'),
  ('Maxus', 'G10', 'extra_large'),
  ('Maxus', 'G50', 'extra_large'),
  ('Maxus', 'D60', 'medium'),
  ('Maxus', 'T60', 'large'),
  ('Maxus', 'Deliver 9', 'extra_large'),
  ('Maxus', 'Mifa 9', 'extra_large'),
  ('Mazda', 'Mazda2', 'small'),
  ('Mazda', 'Mazda3', 'small'),
  ('Mazda', 'CX-3', 'medium'),
  ('Mazda', 'CX-30', 'medium'),
  ('Mazda', 'CX-5', 'large'),
  ('Mazda', 'CX-60', 'large'),
  ('Mazda', 'CX-8', 'large'),
  ('Mazda', 'CX-9', 'large'),
  ('Mazda', 'BT-50', 'large'),
  ('Mazda', 'MX-5', 'small'),
  ('Mazda', 'Mazda6', 'medium'),
  ('Mazda', 'Familia', 'small'),
  ('Mazda', '323', 'small'),
  ('Mazda', '626', 'medium'),
  ('Mazda', 'Premacy', 'medium'),
  ('Mazda', 'MPV', 'large'),
  ('Mazda', 'CX-7', 'large'),
  ('Mazda', 'RX-8', 'small'),
  ('Mercedes-Benz', 'A-Class', 'small'),
  ('Mercedes-Benz', 'C-Class', 'medium'),
  ('Mercedes-Benz', 'E-Class', 'large'),
  ('Mercedes-Benz', 'S-Class', 'large'),
  ('Mercedes-Benz', 'GLA', 'medium'),
  ('Mercedes-Benz', 'GLB', 'medium'),
  ('Mercedes-Benz', 'GLC', 'large'),
  ('Mercedes-Benz', 'GLE', 'large'),
  ('Mercedes-Benz', 'GLS', 'extra_large'),
  ('Mercedes-Benz', 'V-Class', 'extra_large'),
  ('Mercedes-Benz', 'G-Class', 'extra_large'),
  ('Mercedes-Benz', 'CLA', 'small'),
  ('MG', 'MG5', 'small'),
  ('MG', 'ZS', 'medium'),
  ('MG', 'HS', 'large'),
  ('MG', 'RX5', 'medium'),
  ('MG', 'GT', 'small'),
  ('MG', 'One', 'medium'),
  ('MG', 'Cyberster', 'small'),
  ('MG', 'G50', 'extra_large'),
  ('MG', 'V80', 'extra_large'),
  ('MG', '3', 'small'),
  ('MG', '6', 'small'),
  ('MG', 'RX8', 'large'),
  ('Mitsubishi', 'Mirage', 'small'),
  ('Mitsubishi', 'Mirage G4', 'small'),
  ('Mitsubishi', 'Xpander', 'medium'),
  ('Mitsubishi', 'Xpander Cross', 'medium'),
  ('Mitsubishi', 'Montero Sport', 'large'),
  ('Mitsubishi', 'Pajero', 'large'),
  ('Mitsubishi', 'Pajero Sport', 'large'),
  ('Mitsubishi', 'Strada', 'large'),
  ('Mitsubishi', 'L300', 'extra_large'),
  ('Mitsubishi', 'Adventure', 'large'),
  ('Mitsubishi', 'Lancer', 'small'),
  ('Mitsubishi', 'Lancer Evolution', 'small'),
  ('Mitsubishi', 'Galant', 'medium'),
  ('Mitsubishi', 'Space Wagon', 'large'),
  ('Mitsubishi', 'Outlander', 'large'),
  ('Mitsubishi', 'Eclipse Cross', 'medium'),
  ('Mitsubishi', 'ASX', 'medium'),
  ('Mitsubishi', 'Triton', 'large'),
  ('Mitsubishi', 'Delica', 'extra_large'),
  ('Mitsubishi', 'Attrage', 'small'),
  ('Mitsubishi', 'Fuzion', 'medium'),
  ('Nissan', 'Almera', 'small'),
  ('Nissan', 'Kicks', 'medium'),
  ('Nissan', 'Terra', 'large'),
  ('Nissan', 'Navara', 'large'),
  ('Nissan', 'Patrol', 'extra_large'),
  ('Nissan', 'Urvan', 'extra_large'),
  ('Nissan', 'Livina', 'medium'),
  ('Nissan', 'Juke', 'medium'),
  ('Nissan', 'X-Trail', 'large'),
  ('Nissan', 'Sentra', 'small'),
  ('Nissan', 'Cefiro', 'medium'),
  ('Nissan', 'Primera', 'small'),
  ('Nissan', 'Sunny', 'small'),
  ('Nissan', 'Frontier', 'large'),
  ('Nissan', 'Patrol Royale', 'extra_large'),
  ('Nissan', 'GT-R', 'large'),
  ('Nissan', 'Leaf', 'small'),
  ('Nissan', 'Sylphy', 'small'),
  ('Opel', 'Astra', 'small'),
  ('Opel', 'Corsa', 'small'),
  ('Opel', 'Zafira', 'medium'),
  ('Opel', 'Vectra', 'small'),
  ('Peugeot', '2008', 'medium'),
  ('Peugeot', '3008', 'large'),
  ('Peugeot', '5008', 'large'),
  ('Peugeot', 'Landtrek', 'large'),
  ('Peugeot', 'Expert', 'extra_large'),
  ('Peugeot', 'Traveller', 'extra_large'),
  ('Peugeot', '208', 'small'),
  ('Peugeot', '308', 'small'),
  ('Porsche', '911', 'small'),
  ('Porsche', 'Cayenne', 'large'),
  ('Porsche', 'Macan', 'large'),
  ('Porsche', 'Panamera', 'large'),
  ('Porsche', 'Taycan', 'small'),
  ('Porsche', '718', 'small'),
  ('Proton', 'Saga', 'small'),
  ('Proton', 'Persona', 'small'),
  ('Proton', 'X50', 'medium'),
  ('Proton', 'X70', 'large'),
  ('Proton', 'Exora', 'medium'),
  ('Proton', 'Waja', 'small'),
  ('Ssangyong', 'Musso Grand', 'large'),
  ('Ssangyong', 'Rexton Sports', 'large'),
  ('SsangYong', 'Musso', 'large'),
  ('SsangYong', 'Rexton', 'large'),
  ('SsangYong', 'Tivoli', 'medium'),
  ('SsangYong', 'Korando', 'medium'),
  ('SsangYong', 'Actyon', 'large'),
  ('Subaru', 'Impreza', 'small'),
  ('Subaru', 'Legacy', 'medium'),
  ('Subaru', 'Outback', 'large'),
  ('Subaru', 'Forester', 'large'),
  ('Subaru', 'XV', 'medium'),
  ('Subaru', 'Crosstrek', 'medium'),
  ('Subaru', 'WRX', 'small'),
  ('Subaru', 'BRZ', 'small'),
  ('Subaru', 'Ascent', 'large'),
  ('Subaru', 'Levorg', 'medium'),
  ('Suzuki', 'Swift', 'small'),
  ('Suzuki', 'Dzire', 'small'),
  ('Suzuki', 'Ertiga', 'medium'),
  ('Suzuki', 'XL7', 'medium'),
  ('Suzuki', 'Jimny', 'medium'),
  ('Suzuki', 'S-Presso', 'small'),
  ('Suzuki', 'Celerio', 'small'),
  ('Suzuki', 'Vitara', 'medium'),
  ('Suzuki', 'Grand Vitara', 'large'),
  ('Suzuki', 'Carry', 'medium'),
  ('Suzuki', 'APV', 'large'),
  ('Suzuki', 'Alto', 'small'),
  ('Suzuki', 'Wagon R', 'small'),
  ('Suzuki', 'Kizashi', 'small'),
  ('Suzuki', 'SX4', 'medium'),
  ('Suzuki', 'Baleno', 'small'),
  ('Suzuki', 'Ignis', 'small'),
  ('Suzuki', 'S-Cross', 'medium'),
  ('Tesla', 'Model 3', 'small'),
  ('Tesla', 'Model Y', 'medium'),
  ('Tesla', 'Model S', 'large'),
  ('Tesla', 'Model X', 'extra_large'),
  ('Toyota', 'Vios', 'small'),
  ('Toyota', 'Wigo', 'small'),
  ('Toyota', 'Raize', 'medium'),
  ('Toyota', 'Yaris', 'small'),
  ('Toyota', 'Yaris Cross', 'medium'),
  ('Toyota', 'Corolla', 'small'),
  ('Toyota', 'Corolla Altis', 'small'),
  ('Toyota', 'Corolla Cross', 'medium'),
  ('Toyota', 'Camry', 'medium'),
  ('Toyota', 'Innova', 'large'),
  ('Toyota', 'Fortuner', 'large'),
  ('Toyota', 'Rush', 'medium'),
  ('Toyota', 'Avanza', 'medium'),
  ('Toyota', 'Veloz', 'medium'),
  ('Toyota', 'Hilux', 'large'),
  ('Toyota', 'Land Cruiser', 'extra_large'),
  ('Toyota', 'Land Cruiser Prado', 'large'),
  ('Toyota', 'Hiace', 'extra_large'),
  ('Toyota', 'Lite Ace', 'extra_large'),
  ('Toyota', 'Commuter', 'extra_large'),
  ('Toyota', 'Grandia', 'extra_large'),
  ('Toyota', 'Alphard', 'extra_large'),
  ('Toyota', 'Granvia', 'extra_large'),
  ('Toyota', 'Rav4', 'large'),
  ('Toyota', 'C-HR', 'medium'),
  ('Toyota', 'bZ4X', 'medium'),
  ('Toyota', 'Tamaraw FX', 'extra_large'),
  ('Toyota', 'Revo', 'large'),
  ('Toyota', 'Tamaraw', 'extra_large'),
  ('Toyota', 'Corona', 'small'),
  ('Toyota', 'Soluna', 'small'),
  ('Toyota', 'Echo', 'small'),
  ('Toyota', 'Wish', 'large'),
  ('Toyota', 'Previa', 'extra_large'),
  ('Toyota', 'Sienna', 'extra_large'),
  ('Toyota', '86', 'small'),
  ('Toyota', 'GR86', 'small'),
  ('Toyota', 'Supra', 'large'),
  ('Toyota', 'Prius', 'small'),
  ('Toyota', 'Crown', 'large'),
  ('Toyota', 'Coaster', 'extra_large'),
  ('VinFast', 'VF 5', 'small'),
  ('VinFast', 'VF 6', 'medium'),
  ('VinFast', 'VF 7', 'medium'),
  ('VinFast', 'VF 8', 'large'),
  ('VinFast', 'VF 9', 'large'),
  ('VinFast', 'VF e34', 'medium'),
  ('Volkswagen', 'Polo', 'small'),
  ('Volkswagen', 'Golf', 'small'),
  ('Volkswagen', 'Jetta', 'small'),
  ('Volkswagen', 'Tiguan', 'large'),
  ('Volkswagen', 'Teramont', 'extra_large'),
  ('Volkswagen', 'T-Cross', 'medium'),
  ('Volkswagen', 'Passat', 'medium'),
  ('Volkswagen', 'Touareg', 'extra_large'),
  ('Volkswagen', 'Multivan', 'extra_large'),
  ('Volvo', 'XC40', 'medium'),
  ('Volvo', 'XC60', 'large'),
  ('Volvo', 'XC90', 'large'),
  ('Volvo', 'S60', 'medium'),
  ('Volvo', 'S90', 'large'),
  ('Volvo', 'C40', 'medium'),
  ('Volvo', 'EX30', 'medium'),
  ('Volvo', 'EX90', 'large'),
  ('Wuling', 'Almaz', 'large'),
  ('Wuling', 'Cortez', 'extra_large'),
  ('Wuling', 'Confero', 'extra_large'),
  ('Wuling', 'Air Ev', 'small'),
  ('Wuling', 'Binguo Ev', 'small'),
  ('Wuling', 'Mini Ev', 'small'),
  ('Yamaha', 'NMAX', 'small'),
  ('Yamaha', 'Aerox', 'small'),
  ('Yamaha', 'Mio', 'small'),
  ('Yamaha', 'Sniper', 'small'),
  ('Yamaha', 'MT-15', 'small'),
  ('Yamaha', 'R15', 'small'),
  ('Yamaha', 'XSR155', 'small'),
  ('Yamaha', 'Mio i 125', 'small')
) as v(make, model, size_slug)
where lower(vc.make) = lower(v.make)
  and lower(vc.model) = lower(v.model);

-- Seed size matrix for active catalog rows missing any size price (bay wash/packages/addons).
-- Do not overwrite existing detailing matrices.
insert into public.service_size_prices (service_id, size_slug, price_minor)
select s.id, sz.slug,
  case sz.slug
    when 'small' then round(coalesce(s.price_minor, 0) * 0.85)::int
    when 'medium' then coalesce(s.price_minor, 0)
    when 'large' then round(coalesce(s.price_minor, 0) * 1.2)::int
    when 'extra_large' then round(coalesce(s.price_minor, 0) * 1.4)::int
  end
from public.services s
cross join (values ('small'), ('medium'), ('large'), ('extra_large')) as sz(slug)
where s.is_archived = false
  and not exists (
    select 1 from public.service_size_prices ssp where ssp.service_id = s.id
  )
on conflict (service_id, size_slug) do nothing;
