-- PH vehicle catalog full seed (1990s–present common market models)
-- Generated from src/lib/phVehicles.js · 492 make/model pairs

insert into public.vehicle_catalog (make, model, sort_order) values
('Audi', 'A3', 0),
('Audi', 'A4', 1),
('Audi', 'A6', 2),
('Audi', 'Q2', 3),
('Audi', 'Q3', 4),
('Audi', 'Q5', 5),
('Audi', 'Q7', 6),
('Audi', 'Q8', 7),
('Audi', 'e-tron', 8),
('Audi', 'A5', 9),
('Audi', 'TT', 10),
('BAIC', 'X55', 0),
('BAIC', 'BJ40', 1),
('BAIC', 'EU5', 2),
('BAIC', 'Beijing X7', 3),
('BMW', '1 Series', 0),
('BMW', '2 Series', 1),
('BMW', '3 Series', 2),
('BMW', '5 Series', 3),
('BMW', '7 Series', 4),
('BMW', 'X1', 5),
('BMW', 'X3', 6),
('BMW', 'X5', 7),
('BMW', 'X6', 8),
('BMW', 'X7', 9),
('BMW', 'iX', 10),
('BMW', 'i4', 11),
('BMW', 'iX3', 12),
('BYD', 'Atto 3', 0),
('BYD', 'Seal', 1),
('BYD', 'Sealion 6', 2),
('BYD', 'Sealion 7', 3),
('BYD', 'Dolphin', 4),
('BYD', 'Tang', 5),
('BYD', 'Han', 6),
('BYD', 'Shark', 7),
('BYD', 'M6', 8),
('BYD', 'eMAX 7', 9),
('BYD', 'Seal U', 10),
('Changan', 'Alsvin', 0),
('Changan', 'CS15', 1),
('Changan', 'CS35 Plus', 2),
('Changan', 'CS55 Plus', 3),
('Changan', 'UNI-T', 4),
('Changan', 'UNI-V', 5),
('Changan', 'Hunter', 6),
('Changan', 'Nevo A05', 7),
('Chery', 'Tiggo 2 Pro', 0),
('Chery', 'Tiggo 4 Pro', 1),
('Chery', 'Tiggo 5x', 2),
('Chery', 'Tiggo 7 Pro', 3),
('Chery', 'Tiggo 8 Pro', 4),
('Chery', 'Arrizo 5', 5),
('Chery', 'Omoda 5', 6),
('Chery', 'Omoda E5', 7),
('Chery', 'Jaecoo J7', 8),
('Chery', 'QQ', 9),
('Chevrolet', 'Spark', 0),
('Chevrolet', 'Sail', 1),
('Chevrolet', 'Trailblazer', 2),
('Chevrolet', 'Colorado', 3),
('Chevrolet', 'Suburban', 4),
('Chevrolet', 'Tahoe', 5),
('Chevrolet', 'Captiva', 6),
('Chevrolet', 'Aveo', 7),
('Chevrolet', 'Optra', 8),
('Chevrolet', 'Cruze', 9),
('Chevrolet', 'Orlando', 10),
('Chevrolet', 'Spin', 11),
('Chevrolet', 'Tavera', 12),
('Chevrolet', 'Blazer', 13),
('Chrysler', '300C', 0),
('Chrysler', 'PT Cruiser', 1),
('Chrysler', 'Voyager', 2),
('Chrysler', 'Grand Voyager', 3),
('Daihatsu', 'Terios', 0),
('Daihatsu', 'Xenia', 1),
('Daihatsu', 'Gran Max', 2),
('Daihatsu', 'Hijet', 3),
('Daihatsu', 'Rocky', 4),
('DFSK', 'Glory 580', 0),
('DFSK', 'Glory i-Auto', 1),
('DFSK', 'Gelora', 2),
('DFSK', 'C37', 3),
('DFSK', 'Super Cab', 4),
('Dodge', 'Journey', 0),
('Dodge', 'Durango', 1),
('Dodge', 'Challenger', 2),
('Dodge', 'Ram', 3),
('Dongfeng', 'Rich', 0),
('Dongfeng', 'AX7', 1),
('Dongfeng', 'Glory', 2),
('Dongfeng', 'Captain', 3),
('Dongfeng', 'Mango', 4),
('Dongfeng', 'Nammi 01', 5),
('Ford', 'Ranger', 0),
('Ford', 'Everest', 1),
('Ford', 'Territory', 2),
('Ford', 'Explorer', 3),
('Ford', 'Mustang', 4),
('Ford', 'Transit', 5),
('Ford', 'Bronco', 6),
('Ford', 'EcoSport', 7),
('Ford', 'Escape', 8),
('Ford', 'Focus', 9),
('Ford', 'Fiesta', 10),
('Ford', 'Laser', 11),
('Ford', 'Lynx', 12),
('Ford', 'Ranger Raptor', 13),
('Ford', 'Expedition', 14),
('Ford', 'F-150', 15),
('Foton', 'Toplander', 0),
('Foton', 'Thunder', 1),
('Foton', 'View', 2),
('Foton', 'Transvan', 3),
('Foton', 'Gratour', 4),
('Foton', 'Tornado', 5),
('Foton', 'Sauvana', 6),
('Fuso', 'Canter', 0),
('Fuso', 'Fighter', 1),
('Fuso', 'Rosa', 2),
('GAC', 'GS3', 0),
('GAC', 'GS4', 1),
('GAC', 'Emzoom', 2),
('GAC', 'Emkoo', 3),
('GAC', 'M8', 4),
('GAC', 'GN8', 5),
('GAC', 'Aion Y', 6),
('GAC', 'Aion V', 7),
('Geely', 'Coolray', 0),
('Geely', 'Okavango', 1),
('Geely', 'Emgrand', 2),
('Geely', 'GX3 Pro', 3),
('Geely', 'Azkarra', 4),
('Geely', 'Geometry C', 5),
('Geely', 'Preface', 6),
('Geely', 'Monjaro', 7),
('Great Wall', 'Cannon', 0),
('Great Wall', 'Poer', 1),
('Great Wall', 'Wingle', 2),
('Great Wall', 'Steed', 3),
('GWM', 'Cannon', 0),
('GWM', 'Haval H6', 1),
('GWM', 'Haval Jolion', 2),
('GWM', 'Tank 300', 3),
('GWM', 'Ora Good Cat', 4),
('GWM', 'Poer', 5),
('GWM', 'Wey', 6),
('Haima', 'M3', 0),
('Haima', 'S5', 1),
('Haima', '7X', 2),
('Haima', '8S', 3),
('Hino', '300 Series', 0),
('Hino', '500 Series', 1),
('Hino', 'Dutro', 2),
('Hino', 'Ranger', 3),
('Honda', 'Brio', 0),
('Honda', 'City', 1),
('Honda', 'Civic', 2),
('Honda', 'Civic Type R', 3),
('Honda', 'HR-V', 4),
('Honda', 'BR-V', 5),
('Honda', 'CR-V', 6),
('Honda', 'WR-V', 7),
('Honda', 'Accord', 8),
('Honda', 'Mobilio', 9),
('Honda', 'Jazz', 10),
('Honda', 'Fit', 11),
('Honda', 'Pilot', 12),
('Honda', 'Odyssey', 13),
('Honda', 'Pilot Hybrid', 14),
('Honda', 'City Hatchback', 15),
('Honda', 'CR-Z', 16),
('Honda', 'Insight', 17),
('Hyundai', 'Accent', 0),
('Hyundai', 'Reina', 1),
('Hyundai', 'i10', 2),
('Hyundai', 'i20', 3),
('Hyundai', 'Getz', 4),
('Hyundai', 'Eon', 5),
('Hyundai', 'Venue', 6),
('Hyundai', 'Creta', 7),
('Hyundai', 'Tucson', 8),
('Hyundai', 'Santa Fe', 9),
('Hyundai', 'Stargazer', 10),
('Hyundai', 'Stargazer X', 11),
('Hyundai', 'Staria', 12),
('Hyundai', 'Palisade', 13),
('Hyundai', 'Kona', 14),
('Hyundai', 'Elantra', 15),
('Hyundai', 'Sonata', 16),
('Hyundai', 'Ioniq 5', 17),
('Hyundai', 'Ioniq 6', 18),
('Hyundai', 'H100', 19),
('Hyundai', 'H-1', 20),
('Hyundai', 'Grand Starex', 21),
('Hyundai', 'Porter', 22),
('Isuzu', 'D-Max', 0),
('Isuzu', 'mu-X', 1),
('Isuzu', 'Traviz', 2),
('Isuzu', 'Crosswind', 3),
('Isuzu', 'Hi-Lander', 4),
('Isuzu', 'Trooper', 5),
('Isuzu', 'Panther', 6),
('Isuzu', 'N-Series', 7),
('Isuzu', 'F-Series', 8),
('Isuzu', 'Elf', 9),
('Isuzu', 'NPR', 10),
('JAC', 'T8', 0),
('JAC', 'JS4', 1),
('JAC', 'X200', 2),
('JAC', 'Sunray', 3),
('Jeep', 'Wrangler', 0),
('Jeep', 'Gladiator', 1),
('Jeep', 'Cherokee', 2),
('Jeep', 'Grand Cherokee', 3),
('Jeep', 'Compass', 4),
('Jeep', 'Renegade', 5),
('Jetour', 'Dashing', 0),
('Jetour', 'X70', 1),
('Jetour', 'X70 Plus', 2),
('Jetour', 'X90 Plus', 3),
('Jetour', 'T2', 4),
('Jetour', 'Dashing i-DM', 5),
('Kawasaki', 'Barako', 0),
('Kawasaki', 'Rouser', 1),
('Kawasaki', 'Ninja 400', 2),
('Kawasaki', 'Z400', 3),
('Kawasaki', 'KLX', 4),
('Kawasaki', 'CT100', 5),
('Kia', 'Soluto', 0),
('Kia', 'Rio', 1),
('Kia', 'Seltos', 2),
('Kia', 'Sportage', 3),
('Kia', 'Sorento', 4),
('Kia', 'Carnival', 5),
('Kia', 'Picanto', 6),
('Kia', 'Stonic', 7),
('Kia', 'Pride', 8),
('Kia', 'Spectra', 9),
('Kia', 'Carens', 10),
('Kia', 'Soul', 11),
('Kia', 'Forte', 12),
('Kia', 'K5', 13),
('Kia', 'EV6', 14),
('Kia', 'EV9', 15),
('Kia', 'Besta', 16),
('Kia', 'Pregio', 17),
('Lexus', 'IS', 0),
('Lexus', 'ES', 1),
('Lexus', 'LS', 2),
('Lexus', 'NX', 3),
('Lexus', 'RX', 4),
('Lexus', 'UX', 5),
('Lexus', 'LX', 6),
('Lexus', 'LM', 7),
('Lexus', 'GX', 8),
('Lexus', 'RC', 9),
('Mahindra', 'XUV300', 0),
('Mahindra', 'XUV500', 1),
('Mahindra', 'Scorpio', 2),
('Mahindra', 'Bolero', 3),
('Mahindra', 'Thar', 4),
('Mahindra', 'KUV100', 5),
('Maxus', 'G10', 0),
('Maxus', 'G50', 1),
('Maxus', 'D60', 2),
('Maxus', 'T60', 3),
('Maxus', 'Deliver 9', 4),
('Maxus', 'Mifa 9', 5),
('Mazda', 'Mazda2', 0),
('Mazda', 'Mazda3', 1),
('Mazda', 'CX-3', 2),
('Mazda', 'CX-30', 3),
('Mazda', 'CX-5', 4),
('Mazda', 'CX-60', 5),
('Mazda', 'CX-8', 6),
('Mazda', 'CX-9', 7),
('Mazda', 'BT-50', 8),
('Mazda', 'MX-5', 9),
('Mazda', 'Mazda6', 10),
('Mazda', 'Familia', 11),
('Mazda', '323', 12),
('Mazda', '626', 13),
('Mazda', 'Premacy', 14),
('Mazda', 'MPV', 15),
('Mazda', 'CX-7', 16),
('Mazda', 'RX-8', 17),
('Mercedes-Benz', 'A-Class', 0),
('Mercedes-Benz', 'C-Class', 1),
('Mercedes-Benz', 'E-Class', 2),
('Mercedes-Benz', 'S-Class', 3),
('Mercedes-Benz', 'GLA', 4),
('Mercedes-Benz', 'GLB', 5),
('Mercedes-Benz', 'GLC', 6),
('Mercedes-Benz', 'GLE', 7),
('Mercedes-Benz', 'GLS', 8),
('Mercedes-Benz', 'V-Class', 9),
('Mercedes-Benz', 'G-Class', 10),
('Mercedes-Benz', 'CLA', 11),
('MG', 'MG5', 0),
('MG', 'ZS', 1),
('MG', 'HS', 2),
('MG', 'RX5', 3),
('MG', 'GT', 4),
('MG', 'One', 5),
('MG', 'Cyberster', 6),
('MG', 'G50', 7),
('MG', 'V80', 8),
('MG', '3', 9),
('MG', '6', 10),
('MG', 'RX8', 11),
('Mitsubishi', 'Mirage', 0),
('Mitsubishi', 'Mirage G4', 1),
('Mitsubishi', 'Xpander', 2),
('Mitsubishi', 'Xpander Cross', 3),
('Mitsubishi', 'Montero Sport', 4),
('Mitsubishi', 'Pajero', 5),
('Mitsubishi', 'Pajero Sport', 6),
('Mitsubishi', 'Strada', 7),
('Mitsubishi', 'L300', 8),
('Mitsubishi', 'Adventure', 9),
('Mitsubishi', 'Lancer', 10),
('Mitsubishi', 'Lancer Evolution', 11),
('Mitsubishi', 'Galant', 12),
('Mitsubishi', 'Space Wagon', 13),
('Mitsubishi', 'Outlander', 14),
('Mitsubishi', 'Eclipse Cross', 15),
('Mitsubishi', 'ASX', 16),
('Mitsubishi', 'Triton', 17),
('Mitsubishi', 'Delica', 18),
('Mitsubishi', 'Attrage', 19),
('Mitsubishi', 'Fuzion', 20),
('Nissan', 'Almera', 0),
('Nissan', 'Kicks', 1),
('Nissan', 'Terra', 2),
('Nissan', 'Navara', 3),
('Nissan', 'Patrol', 4),
('Nissan', 'Urvan', 5),
('Nissan', 'Livina', 6),
('Nissan', 'Juke', 7),
('Nissan', 'X-Trail', 8),
('Nissan', 'Sentra', 9),
('Nissan', 'Cefiro', 10),
('Nissan', 'Primera', 11),
('Nissan', 'Sunny', 12),
('Nissan', 'Frontier', 13),
('Nissan', 'Patrol Royale', 14),
('Nissan', 'GT-R', 15),
('Nissan', 'Leaf', 16),
('Nissan', 'Sylphy', 17),
('Opel', 'Astra', 0),
('Opel', 'Corsa', 1),
('Opel', 'Zafira', 2),
('Opel', 'Vectra', 3),
('Peugeot', '2008', 0),
('Peugeot', '3008', 1),
('Peugeot', '5008', 2),
('Peugeot', 'Landtrek', 3),
('Peugeot', 'Expert', 4),
('Peugeot', 'Traveller', 5),
('Peugeot', '208', 6),
('Peugeot', '308', 7),
('Porsche', '911', 0),
('Porsche', 'Cayenne', 1),
('Porsche', 'Macan', 2),
('Porsche', 'Panamera', 3),
('Porsche', 'Taycan', 4),
('Porsche', '718', 5),
('Proton', 'Saga', 0),
('Proton', 'Persona', 1),
('Proton', 'X50', 2),
('Proton', 'X70', 3),
('Proton', 'Exora', 4),
('Proton', 'Waja', 5),
('Ssangyong', 'Musso Grand', 0),
('Ssangyong', 'Rexton Sports', 1),
('SsangYong', 'Musso', 0),
('SsangYong', 'Rexton', 1),
('SsangYong', 'Tivoli', 2),
('SsangYong', 'Korando', 3),
('SsangYong', 'Actyon', 4),
('Subaru', 'Impreza', 0),
('Subaru', 'Legacy', 1),
('Subaru', 'Outback', 2),
('Subaru', 'Forester', 3),
('Subaru', 'XV', 4),
('Subaru', 'Crosstrek', 5),
('Subaru', 'WRX', 6),
('Subaru', 'BRZ', 7),
('Subaru', 'Ascent', 8),
('Subaru', 'Levorg', 9),
('Suzuki', 'Swift', 0),
('Suzuki', 'Dzire', 1),
('Suzuki', 'Ertiga', 2),
('Suzuki', 'XL7', 3),
('Suzuki', 'Jimny', 4),
('Suzuki', 'S-Presso', 5),
('Suzuki', 'Celerio', 6),
('Suzuki', 'Vitara', 7),
('Suzuki', 'Grand Vitara', 8),
('Suzuki', 'Carry', 9),
('Suzuki', 'APV', 10),
('Suzuki', 'Alto', 11),
('Suzuki', 'Wagon R', 12),
('Suzuki', 'Kizashi', 13),
('Suzuki', 'SX4', 14),
('Suzuki', 'Baleno', 15),
('Suzuki', 'Ignis', 16),
('Suzuki', 'S-Cross', 17),
('Tesla', 'Model 3', 0),
('Tesla', 'Model Y', 1),
('Tesla', 'Model S', 2),
('Tesla', 'Model X', 3),
('Toyota', 'Vios', 0),
('Toyota', 'Wigo', 1),
('Toyota', 'Raize', 2),
('Toyota', 'Yaris', 3),
('Toyota', 'Yaris Cross', 4),
('Toyota', 'Corolla', 5),
('Toyota', 'Corolla Altis', 6),
('Toyota', 'Corolla Cross', 7),
('Toyota', 'Camry', 8),
('Toyota', 'Innova', 9),
('Toyota', 'Fortuner', 10),
('Toyota', 'Rush', 11),
('Toyota', 'Avanza', 12),
('Toyota', 'Veloz', 13),
('Toyota', 'Hilux', 14),
('Toyota', 'Land Cruiser', 15),
('Toyota', 'Land Cruiser Prado', 16),
('Toyota', 'Hiace', 17),
('Toyota', 'Lite Ace', 18),
('Toyota', 'Commuter', 19),
('Toyota', 'Grandia', 20),
('Toyota', 'Alphard', 21),
('Toyota', 'Granvia', 22),
('Toyota', 'Rav4', 23),
('Toyota', 'C-HR', 24),
('Toyota', 'bZ4X', 25),
('Toyota', 'Tamaraw FX', 26),
('Toyota', 'Revo', 27),
('Toyota', 'Tamaraw', 28),
('Toyota', 'Corona', 29),
('Toyota', 'Soluna', 30),
('Toyota', 'Echo', 31),
('Toyota', 'Wish', 32),
('Toyota', 'Previa', 33),
('Toyota', 'Sienna', 34),
('Toyota', '86', 35),
('Toyota', 'GR86', 36),
('Toyota', 'Supra', 37),
('Toyota', 'Prius', 38),
('Toyota', 'Crown', 39),
('Toyota', 'Coaster', 40),
('VinFast', 'VF 5', 0),
('VinFast', 'VF 6', 1),
('VinFast', 'VF 7', 2),
('VinFast', 'VF 8', 3),
('VinFast', 'VF 9', 4),
('VinFast', 'VF e34', 5),
('Volkswagen', 'Polo', 0),
('Volkswagen', 'Golf', 1),
('Volkswagen', 'Jetta', 2),
('Volkswagen', 'Tiguan', 3),
('Volkswagen', 'Teramont', 4),
('Volkswagen', 'T-Cross', 5),
('Volkswagen', 'Passat', 6),
('Volkswagen', 'Touareg', 7),
('Volkswagen', 'Multivan', 8),
('Volvo', 'XC40', 0),
('Volvo', 'XC60', 1),
('Volvo', 'XC90', 2),
('Volvo', 'S60', 3),
('Volvo', 'S90', 4),
('Volvo', 'C40', 5),
('Volvo', 'EX30', 6),
('Volvo', 'EX90', 7),
('Wuling', 'Almaz', 0),
('Wuling', 'Cortez', 1),
('Wuling', 'Confero', 2),
('Wuling', 'Air Ev', 3),
('Wuling', 'Binguo Ev', 4),
('Wuling', 'Mini Ev', 5),
('Yamaha', 'NMAX', 0),
('Yamaha', 'Aerox', 1),
('Yamaha', 'Mio', 2),
('Yamaha', 'Sniper', 3),
('Yamaha', 'MT-15', 4),
('Yamaha', 'R15', 5),
('Yamaha', 'XSR155', 6),
('Yamaha', 'Mio i 125', 7)
on conflict (make, model) do update
set sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();
